### ISSUE TITLE
Error from library during compilation

### ISSUE THREAD

**Issue by deepu105** [davidB/kubectl-view-allocations#173]
I'm starting to see the below error when updating to v0.14.8. I'm investigating it currently.

```
error[E0405]: cannot find trait `CommandFactory` in crate `clap`
   --> /home/deepu/.cargo/registry/src/github.com-1ecc6299db9ec823/kubectl-view-allocations-0.14.8/src/lib.rs:558:10
    |
558 | #[derive(Parser, Debug)]
    |          ^^^^^^ not found in `clap`
    |
    = note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `Command` in crate `clap`
   --> /home/deepu/.cargo/registry/src/github.com-1ecc6299db9ec823/kubectl-view-allocations-0.14.8/src/lib.rs:558:10
    |
558 | #[derive(Parser, Debug)]
    |          ^^^^^^ not found in `clap`
    |
    = note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
    |
6   | use std::process::Command;
    |

error[E0433]: failed to resolve: could not find `Command` in `clap`
   --> /home/deepu/.cargo/registry/src/github.com-1ecc6299db9ec823/kubectl-view-allocations-0.14.8/src/lib.rs:558:10
    |
558 | #[derive(Parser, Debug)]
    |          ^^^^^^ not found in `clap`
    |
    = note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing this struct
    |
6   | use std::process::Command;
    |

Some errors have detailed explanations: E0405, E0412, E0433.
```

**Comment by deepu105** [comment]
Nevermind, seems to go away when upgrading clap on my prokect
